<?php

namespace app\index\controller;

use app\http\middleware\IndexCheckIp;
use think\Controller;
use think\Exception;
use think\facade\Session;
use think\Request;
use think\Response;
use app\index\model\User as UserModel;
use app\index\model\UserIntegralHistory as IntegralHistoryModel;
use app\index\model\ForumPlate as PlateModel;

class Base extends Controller
{
    protected $middleware = [
        IndexCheckIp::class,
    ];

    const WEB_SITE_PATH = CONFIG_PATH . 'web_site.json';        //网站配置路径

    private $configObject = null;

    private $userInfo = [];

    protected $userInfoSessionPath = null;   // 用户session 存储路径

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->userInfoSessionPath = config('app.index_user_session_path');

        $this->getUserInfo();

        $this->loadingPublicData(\think\facade\Request::instance());
    }

    protected function getUserInfo()
    {
        $user_info = Session::get($this->userInfoSessionPath);
        if ($user_info) {
            $this->userInfo = (new UserModel())->where(['id' => $user_info['id'], 'is_delete' => 1])->find();
        }
    }

    /**
     * 加载公共数据
     * @param Request $request
     */
    private function loadingPublicData(Request $request)
    {
        if (!$request->isAjax()){
            //查询社区分类
            $this->assign('forum_plate_list',(new PlateModel())->getList());
            //查询用户信息
            $this->assign('user_info',$this->userInfo);
            //右面浮动栏数据
            $this->assign('qq',$this->getConfig('qq'));             //公告
            $this->assign('phone',$this->getConfig('phone'));             //公告
            $this->assign('qr_code',$this->getConfig('qr_code'));
            //网站标题
            $this->assign('website_title',$this->getConfig('title'));
            //网站meta信息
            $this->assign('website_keywords',$this->getConfig('keyword'));
            $this->assign('website_description',$this->getConfig('description'));
            //版权与备案号
            $this->assign('website_copyright',$this->getConfig('copyright'));
            $this->assign('website_icp',$this->getConfig('icp'));
        }
    }

    public function __get($name)
    {
        // TODO: Implement __get() method.
        if ($name == 'userInfo'){
            if (!$this->$name) {
                if (\request()->isAjax()){
                    header('Content-type: application/json');
                    exit(json_encode(['code' => 0, 'msg' => '请先登陆账号~'], 256));
                }else{
                    return $this->redirect('index');
                }
            }
            return $this->$name;
        }
    }

    /**
     * 添加 积分变动记录到表中
     * @param $integral
     */
    protected function addUserIntegralHistory($type, $integral,$user_id = null)
    {
        $user_id = $user_id ? $user_id : $this->userInfo['id'];

        $result = [
            'type' => $type,
            'integral' => $integral,
            'user_id' => $user_id,
            'create_time' => time(),
        ];
        (new IntegralHistoryModel())->insert($result);
        $upArr = [1, 2, 5, 6, 7, 8, 9, 10];
        $downArr = [3, 4];
        $userModel = (new UserModel())->where(['id' => $user_id]);
        if (in_array($type, $upArr)) {
            $userModel->setInc('integral', $integral);
        } else if (in_array($type, $downArr)) {
            $userModel->setDec('integral', $integral);
        }
    }

    /**
     * 获取配置信息
     * @param $name
     * @return mixed|null
     */
    protected function getConfig($name)
    {
        if (!$this->configObject){
            $this->configObject = json_decode(file_get_contents(self::WEB_SITE_PATH));
        }
        $configPath = explode('.', $name);
        $temp = $this->configObject;
        try {
            foreach ($configPath as $key => $value) {
                $temp = $temp->$value;
            }
            if (!$temp) throw new Exception();
        } catch (Exception $e) {
            header('Content-type: application/json');
            exit(json_encode(['code' => 0, 'msg' => '获取配置失败'], 256));
        }
        $temp = json_decode(json_encode($temp,256),true);
        return $temp;
    }
}
