<?php

namespace app\api\controller;

use think\Controller;
use think\Request;
use think\Response;
use app\api\model\User as UserModel;

class Base extends Controller
{
    protected  $userInfo = [];

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->getUserInfo();

    }

    private function getUserInfo()
    {
        $token = request()->post('token');
        if ($token){
            $this->userInfo = (new UserModel())->where(['token'=>$token])->find();
            if (!$this->userInfo){
                header('Content-type: application/json');
                exit(json_encode(['code'=>0,'msg'=>'获取用户信息失败'],256));
            }
        }
    }


}
