<?php

namespace app\api\controller;

use think\Controller;
use think\Request;
use think\Response;
use app\api\model\User as UserModel;
use app\api\model\UserIntegralHistory as IntegralHistoryModel;

class Base extends Controller
{
    private $userInfo = [];

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->getUserInfo();

    }

    private function getUserInfo()
    {
        $token = request()->post('token');
        if ($token){
            $this->userInfo = (new UserModel())->where(['token'=>$token])->find();
            if (!$this->userInfo){
                header('Content-type: application/json');
                exit(json_encode(['code'=>0,'msg'=>'获取用户信息失败'],256));
            }
        }
    }

    public function __get($name)
    {
        // TODO: Implement __get() method.
        if (!$this->$name){
            header('Content-type: application/json');
            exit(json_encode(['code'=>0,'msg'=>'获取用户信息失败'],256));
        }
        return $this->$name;
    }

    /**
     * 添加 积分变动记录到表中
     * @param $integral
     */
    protected function addUserIntegralHistory($type,$integral)
    {
        $result = [
            'type'  => $type,
            'integral' => $integral,
            'user_id'   => $this->userInfo['id'],
            'create_time' => time(),
        ];

        (new IntegralHistoryModel())->insert($result);
    }

}
