<?php
/**
 * Created by PhpStorm.
 * User: 刘彪
 * Date: 2019/8/23
 * Time: 17:23
 */

namespace app\api\controller;


use think\Controller;
use app\api\model\User as UserModel;

class ForumManagerBase extends Controller
{

    const WEB_SITE_PATH = CONFIG_PATH . 'web_site.json';

    private $userInfo = [];

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->getUserInfo();
    }

    private function getUserInfo()
    {

        $token = \think\facade\Request::param('token');
        if ($token) {
            $this->userInfo = (new UserModel())->where(['token' => $token, 'is_delete' => 1])->find();
            if (!$this->userInfo) {
                header('Content-type: application/json');
                exit(json_encode(['code' => 0, 'msg' => '获取用户信息失败'], 256));
            }
        }
    }

    private function getPermissionInfo(){}

    public function __get($name)
    {
        // TODO: Implement __get() method.
        if (!$this->$name) {
            header('Content-type: application/json');
            exit(json_encode(['code' => 0, 'msg' => '获取用户信息失败'], 256));
        }
        return $this->$name;
    }

}