<?php
/**
 * Created by PhpStorm.
 * User: 刘彪
 * Date: 2019/8/26
 * Time: 16:28
 */

namespace app\api\controller;


use think\Request;
use think\Validate;
use app\api\model\Forum as ForumModel;
use app\api\model\ForumComment as ForumCommentModel;
use app\api\model\ForumManager as ForumManagerModel;
use app\api\model\UserCollect as UserCollectModel;
use app\api\model\ForumApplyForManager as ApplyModel;


class MyForum extends Base
{
    public $is_manager = false;     //是否拥有管理员身份


    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        //查看用户是否管理组成员
        $user_id = $this->userInfo['id'];

        $managerInfo = (new ForumManagerModel())->where(['id' => $user_id])->select();

        if ($managerInfo) {
            $this->is_manager = true;
        }
    }

    //我的发布
    public function myPublish(Request $request)
    {
        $data = $request->post();
        $rules = [
            'page' => 'require',
            'page_length' => 'require',

        ];
        $messages = [
            'page.require' => 'page必须携带',
            'page_length.require' => 'page_length必须携带',
        ];
        $validate = new Validate($rules, $messages);
        if (!$validate->check($data)) {
            return json(['code' => 0, 'msg' => $validate->getError()]);
        }
        $user_id = $this->userInfo['id'];
        $start = $data['page'] * $data['page_length'] - $data['page_length'];

        $res = (new ForumModel())->where(['user_id' => $user_id, 'is_delete' => 0]);
        $count = $res->count();
        $res = $res->field('id,name,is_classics,is_top,is_original,pic,see_num,like_num,collect_num,comment_num,create_time')
            ->order('id', 'desc')->limit($start, $data['page_length'])->select();

        return json(['code' => 1, 'data' => $res, 'count' => $count, 'is_manager' => $this->is_manager]);

    }

    //我的回复
    public function myComment(Request $request)
    {
        $data = $request->post();
        $rules = [
            'page' => 'require',
            'page_length' => 'require',
        ];

        $messages = [
            'page.require' => 'page必须携带',
            'page_length.require' => 'page_length必须携带',
        ];
        $validate = new Validate($rules, $messages);
        if (!$validate->check($data)) {
            return json(['code' => 0, 'msg' => $validate->getError()]);
        }
        $start = $data['page'] * $data['page_length'] - $data['page_length'];
        $comment = (new ForumCommentModel())->where(['user_id' => $this->userInfo['id'], 'status' => 1]);

        $commentList = $comment->field('content,status,create_time')->order('id', 'desc')
            ->limit($start, $data['page_length'])
            ->select();

        $count = $comment->count();

        return json(['code' => 1, 'data' => $commentList, 'count' => $count, 'is_manager' => $this->is_manager]);
    }

    //我的收藏
    public function myCollect(Request $request)
    {
        $data = $request->post();
        $rules = [
            'page' => 'require',
            'page_length' => 'require',
        ];

        $messages = [
            'page.require' => 'page必须携带',
            'page_length.require' => 'page_length必须携带',
        ];
        $validate = new Validate($rules, $messages);
        if (!$validate->check($data)) {
            return json(['code' => 0, 'msg' => $validate->getError()]);
        }

        $start = $data['page'] * $data['page_length'] - $data['page_length'];

        $collect = (new UserCollectModel())->alias('collect')->where(['collect.user_id' => $this->userInfo['id']])
            ->where(['type' => '3']);
        $count = $collect->count();
        $collectList = $collect->join('forum forum', 'collect.collect_id = forum.id')
            ->field('forum.name,forum.id,forum.create_time')
            ->order('forum.id', 'desc')
            ->limit($start, $data['page_length'])
            ->select();
        return json(['code' => 1, 'data' => $collectList, 'count' => $count, 'is_manager' => $this->is_manager]);
    }

    //我的申请
    public function myApplyFor(Request $request)
    {
        $data = $request->post();
        $rules = [
            'page' => 'require',
            'page_length' => 'require',
        ];

        $messages = [
            'page.require' => 'page必须携带',
            'page_length.require' => 'page_length必须携带',
        ];
        $validate = new Validate($rules, $messages);
        if (!$validate->check($data)) {
            return json(['code' => 0, 'msg' => $validate->getError()]);
        }

        $start = $data['page'] * $data['page_length'] - $data['page_length'];

        $res = (new ApplyModel())->alias('apply')
            ->join('forum_plate plate', 'plate.id = apply.plate_id')
            ->where(['apply.user_id'=>$this->userInfo['id']]);
        $count = $res->count();
        $res = $res->field('plate.plate_name,apply.apply_for_desc,apply.create_time')
            ->order('apply.id', 'desc')
            ->limit($start, $data['page_length'])
            ->select();

        return json(['code' => 1, 'data' => $res, 'count' => $count]);


    }

    //我的参与
    public function myJoinIn()
    {

    }

    //待审核

    //已通过

    //已拒绝
}